<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount' => 'Сума',
    'Are you sure you want to delete this item?' => 'Ви впевнені що бажаєте видалити?',
    'Authorization' => 'Авторизація',
    'Brand Title' => 'Бренд',
    'Categories' => 'Категорії',
    'Category' => 'Категорія',
    'Category ID' => 'ІД категорії',
    'Client SID' => 'Покупець (Ідентифікатор)',
    'Confirm password' => 'Підтвердження паролю',
    'Create Category' => 'Створити категорию',
    'Create Order' => 'Створити замовлення',
    'Create Product' => 'Створити продукт',
    'Created At' => 'Створено',
    'Current image' => 'Поточне зображення',
    'Dashboard' => 'Адмін панель',
    'Delete' => 'Видалити',
    'Description' => 'Опис',
    'Done order' => 'Завершений',
    'Edit' => 'Редагувати',
    'Editing product categories for display on a public page' => 'Редагування категорій товарів для відображення на публічних сторінках магазину. Додавання категорій. Зміна зображень та назв.',
    'Editing products for display on a public page' => 'Редагування товарів, що відображаються на публічних сторінках магазину. Додавання товарів. Зміна зображень, назв, цін та кількості.',
    'Email' => 'Електронна пошта',
    'ID' => 'ІД',
    'Image' => 'Зображення',
    'Info' => 'Інформація',
    'Login' => 'Логін',
    'Name' => 'Ім\'я',
    'New order' => 'Нове',
    'No' => 'Ні',
    'Order ID' => 'ІД Замовлення',
    'Orders' => 'Замовлення',
    'Password' => 'Пароль',
    'Payed order' => 'Сплачене',
    'Phone' => 'Телефон',
    'Price' => 'Ціна',
    'Product ID' => 'ІД Продукту',
    'Products' => 'Продукти',
    'Quantity' => 'Кількість',
    'Remember me' => 'Запам\'ятати мене',
    'Reset' => 'Скинути',
    'Role' => 'Роль',
    'Save' => 'Зберегти',
    'Search' => 'Пошук',
    'Show' => 'Показати',
    'Sku' => 'КОД',
    'Status' => 'Статус',
    'The requested page does not exist.' => 'Сторінка не існує',
    'Title' => 'Назва',
    'Total amount' => 'Загальна сума',
    'Update' => 'Оновити',
    'Update Category: {name}' => 'Оновити категорию: {name}',
    'Update Order: {name}' => 'Оновити замовлення {name}',
    'Update Product: {name}' => 'Оновити продукт: {name}',
    'Url' => 'Посилання',
    'Username' => 'Логін',
    'Users' => 'Користувачі',
    'Viewing and working with orders from customers' => 'Перегляд та робота із замовленнями клієнтів (зміна статусу, перегляд суми та замовлених товарів)',
    'Work' => 'Працювати',
    'Yes' => 'Так',
];
