<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add to cart' => 'Додати у кошик',
    'All' => 'Усі',
    'Availability' => 'Доступність',
    'Cart' => 'Кошик',
    'Categories' => 'Категорії',
    'Checkout' => 'Оплата',
    'Contact us' => 'Зв\'язатися з нами',
    'Continue shopping' => 'Продовжити покупки',
    'Description' => 'Опис',
    'Grid' => 'Картки',
    'Image' => 'Зображення',
    'In Stock' => 'В наявності',
    'List' => 'Список',
    'New products' => 'Нові продукти',
    'Not Available' => 'Немає на складі',
    'Pay' => 'Сплатити',
    'Price' => 'Ціна',
    'Quantity' => 'Кількість',
    'Remove' => 'Видалити',
    'Review' => 'Огляд',
    'Sort by' => 'Сортувати за',
    'Subtotal' => 'Сума',
    'Title' => 'Назва',
    'Top categories' => 'Кращі категорії',
    'Total' => 'Загальна сума',
    'Total amount' => 'Загальна сума',
];
